version: "3.9"
services:
  web:
    build:
      context: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: fastapi_user
      POSTGRES_PASSWORD: fastapi_password
      POSTGRES_DB: fastapi_db
    ports:
      - "9999:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: