"""column type 변경

Revision ID: 0f79f0694780
Revises: dc05ed59533c
Create Date: 2025-01-08 13:11:50.649759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f79f0694780'
down_revision: Union[str, None] = 'dc05ed59533c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('diaries', 'weather',
               existing_type=postgresql.ENUM('clear', 'some_clouds', 'cloudy', 'rainy', 'snowy', name='weatherenum'),
               nullable=False)
    op.alter_column('diaries', 'mood',
               existing_type=postgresql.ENUM('happy', 'good', 'normal', 'tired', 'sad', name='moodenum'),
               nullable=False)
    op.alter_column('ex_diaries', 'weather',
               existing_type=postgresql.ENUM('clear', 'some_clouds', 'cloudy', 'rainy', 'snowy', name='ex_weatherenum'),
               type_=sa.Enum('clear', 'some_clouds', 'cloudy', 'rainy', 'snowy', name='ex_weatherenum'),
               existing_nullable=True)
    op.alter_column('ex_diaries', 'mood',
               existing_type=postgresql.ENUM('happy', 'good', 'normal', 'tired', 'sad', name='ex_moodenum'),
               type_=sa.Enum('happy', 'good', 'normal', 'tired', 'sad', name='ex_moodenum'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ex_diaries', 'mood',
               existing_type=sa.Enum('happy', 'good', 'normal', 'tired', 'sad', name='moodenum'),
               type_=postgresql.ENUM('happy', 'good', 'normal', 'tired', 'sad', name='ex_moodenum'),
               existing_nullable=True)
    op.alter_column('ex_diaries', 'weather',
               existing_type=sa.Enum('clear', 'some_clouds', 'cloudy', 'rainy', 'snowy', name='weatherenum'),
               type_=postgresql.ENUM('clear', 'some_clouds', 'cloudy', 'rainy', 'snowy', name='ex_weatherenum'),
               existing_nullable=True)
    op.alter_column('diaries', 'mood',
               existing_type=postgresql.ENUM('happy', 'good', 'normal', 'tired', 'sad', name='moodenum'),
               nullable=True)
    op.alter_column('diaries', 'weather',
               existing_type=postgresql.ENUM('clear', 'some_clouds', 'cloudy', 'rainy', 'snowy', name='weatherenum'),
               nullable=True)
    # ### end Alembic commands ###
