"""create Diary table

Revision ID: 380bc1081281
Revises: 9ea12a8244d9
Create Date: 2024-12-30 12:45:18.436002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '380bc1081281'
down_revision: Union[str, None] = '9ea12a8244d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('weather', sa.Enum('clear', 'some_clouds', 'cloudy', 'rainy', 'snowy', name='weatherenum'), nullable=True),
    sa.Column('mood', sa.Enum('happy', 'good', 'normal', 'tired', 'sad', name='moodenum'), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('img_url', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diary')
    # ### end Alembic commands ###
