"""user_diary_relationship

Revision ID: 98a55a606049
Revises: 628aca82e4db
Create Date: 2025-01-03 12:04:23.032207

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "98a55a606049"
down_revision: Union[str, None] = "628aca82e4db"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("diaries_user_id_fkey", "diaries", type_="foreignkey")
    op.create_foreign_key(
        None, "diaries", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "diaries", type_="foreignkey")
    op.create_foreign_key(
        "diaries_user_id_fkey", "diaries", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
