"""create ex_diary table 2501080316

Revision ID: dc05ed59533c
Revises: 48204f176c5a
Create Date: 2025-01-08 03:16:03.962542

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dc05ed59533c"
down_revision: Union[str, None] = "48204f176c5a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ex_diaries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("friend_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("write_date", sa.Date(), nullable=False),
        sa.Column(
            "weather",
            sa.Enum(
                "clear",
                "some_clouds",
                "cloudy",
                "rainy",
                "snowy",
                name="ex_weatherenum",
            ),
            nullable=True,
        ),
        sa.Column(
            "mood",
            sa.Enum("happy", "good", "normal", "tired", "sad", name="ex_moodenum"),
            nullable=True,
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("img_url", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["friend_id"], ["friends.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column("users", "provider", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column("users", "provider", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_table("ex_diaries")
    # ### end Alembic commands ###
