name: CI

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop, feature/* ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: endofday_test
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin_pw
        ports:
          - "9999:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.4'
          
      - name: Install Poetry
        uses: snok/install-poetry@v1
        
      - name: Install dependencies
        run: poetry install

      - name: Run Black
        run: poetry run black . --check

      - name: Run isort
        run: poetry run isort . --check-only

      - name: Run Mypy
        run: poetry run mypy .

      - name: Run Tests
        env:
          DATABASE_URL: postgresql+psycopg2://admin:admin_pw@localhost:9999/endofday_test
          REDIS_HOST: localhost
          REDIS_PORT: 6379
        run: poetry run pytest tests/

      - name: Start server
        env:
          DATABASE_URL: postgresql+psycopg2://admin:admin_pw@localhost:9999/endofday_test
          REDIS_HOST: localhost
          REDIS_PORT: 6379
        run: |
          poetry run uvicorn src.main:app --host 0.0.0.0 --port 8000 &
          sleep 5

      - name: Test Server
        run: |
          curl http://localhost:8000 || exit 1